#!/bin/bash
# chkconfig: 2345 90 10
# description: a self-hosted remote torrent client 

### BEGIN INIT INFO
# Provides:          CloudTorrent
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: a self-hosted remote torrent client 
# Description:       Start or stop the CloudTorrent
### END INIT INFO

# Author: benzBrake <github-benzBrake@woai.ru>

NAME=CloudTorrent
BIN=/usr/local/cloudtorrent/cloud-torrent
CONFIG=/usr/local/cloudtorrent/cloudtorrent.conf
LOGFILE=/var/log/cloudtorrent.log
RETVAL=0
source $CONFIG
check_running(){
    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
    if [ ! -z $PID ]; then
        return 0
    else
        return 1
    fi
}

do_start(){
    check_running
    if [ $? -eq 0 ]; then
        echo "$NAME (pid $PID) is already running..."
        exit 0
    else
        $BIN -p "${CT_PORT}" -l -a "${CT_USER}":"${CT_PASS}" >> cloud-torrent.log 2>&1 &
        check_running
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            echo "Starting $NAME success"
        else
            echo "Starting $NAME failed"
        fi
    fi
}

do_stop(){
    check_running
    if [ $? -eq 0 ]; then
        PID=$( ps -ef | grep cloud-torrent | grep -v grep | awk '{print $2}' )
        ! test -z "$PID" && {
            kill -9 "$PID"
            RETVAL=$?
        }
        if [ $RETVAL -eq 0 ]; then
            echo "Stopping $NAME success"
        else
            echo "Stopping $NAME failed"
        fi
    else
        echo "$NAME is stopped"
        RETVAL=1
    fi
}

do_status(){
    check_running
    if [ $? -eq 0 ]; then
        echo "$NAME (pid $PID) is running..."
    else
        echo "$NAME is stopped"
        RETVAL=1
    fi
}

do_restart(){
    do_stop
    do_start
}

case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    echo "Usage: $0 { start | stop | restart | status }"
    RETVAL=1
    ;;
esac

exit $RETVAL